#!/usr/local/bin/python

import sys
from twilio.rest import TwilioRestClient

def send_text(text):
    # Your Account Sid and Auth Token from twilio.com/user/account
    account_sid = "ACeef6a0ea6dceb539695ad8d28cc841cd"
    auth_token  = "2a0056cc9ffdadc28f89c1a012f0dcdc"
    client = TwilioRestClient(account_sid, auth_token)

    message = client.sms.messages.create(body=text,
                                         to="+17807298784",    # Replace with your phone number
                                         from_="+15874000991")

if __name__ == "__main__":
    for message in sys.argv[1:]:
        send_text(message)
